@startuml
start
while(遍历这一页?)
if (是新一行?) then(是)
if(大于body?) then (是)
:firstOfThisLineIsBigger = true;
else (不是)
:firstOfThisLineIsBigger = false;
endif
endif
if(firstOfThisLineIsBigger = false?) then (是)
:continue;
else (不是)
if(是新一行 ) then (是)
:保存上一行的大于body的内容;
:清空sb;
else (不是)
:追加这个text,不管大于还是小于body;
endif
endif
endwhile
end
@enduml